## Use custom format - fancy
#format = '''
#[RC](white)[ ∶ ](yellow)$directory$rust$package
#[┌───────────────────────────────────────────────────────────────────────────────────────▶](yellow)
#[└▶](yellow) '''

## Custom format - testing
#format = '''
#[](yellow)$directory$rust$package[](yellow)
#[☻ ](yellow)$username[▶](yellow) '''

# format = '''
# $username [in](italic bright-white) $directory$rust$package$git_status$cmd_duration
# $character '''

# format = '''
# $username [→](italic bright-white) $directory$git_status$cmd_duration[←](italic bright-white)
# $character'''

# format = '''
# $time [|](bold bright-white) $directory$git_status$cmd_duration
# $username $character'''

## Custom format - basic
# format = '''
# $username [󱦰](bright-white) $directory$git_status$cmd_duration$fill$time
# $character'''
format = '''
$username [󱦰](bright-white) $directory$git_status$cmd_duration
$time $character'''

add_newline = false

continuation_prompt = '[▶](bright-blue) '

# right_format = '''$time'''

[character]
success_symbol = '[󰭓](green)'
# success_symbol = '[▶](bold bright-white)'
# error_symbol = "[D'oh!](bold red)"
# error_symbol = '[▶](bold red)'
error_symbol = '[󰭓](red)'

[fill]
symbol = ' '

[time]
disabled = false
style = 'bright-white'
time_format = '%I:%M'
# format = '[ $time]($style)'
format = '[$time]($style)'
use_12hr = true

[username]
style_user = 'yellow'
# format = '[ $user]($style)'
format = '[ $user]($style)'
show_always = true
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
show_milliseconds = false
# format = '[took](bright-white) [$duration](bold cyan)'
# format = '[took](italic bright-white) [$duration](bold yellow)'
format = '[󰔚 $duration](bright-white)'
min_time = 5000
# format = 'took [$duration]($style)' - default

[directory]
# style = 'white'
style = 'blue'
home_symbol = ' '
read_only = ' '
 
# Dont do linebreak
[line_break]
# disabled = true
# Disable the blank line at the start of the prompt
# add_newline = false
